### ISSUE TITLE
v2.0.2 not compatibility with victoire 2.x

### ISSUE THREAD

**Issue by BFoucher** [FriendsOfVictoire/WidgetMenuBundle#18]
The 2.0.2 apply changes for victoire 3.x compatibily.
But theses changes are not compatible with version 2.x of victoire.

The 2.0.2 tag should be removed to create a v3 branch.

**Comment by lenybernard** [comment]
I replaced the 2.0.2 by the https://github.com/FriendsOfVictoire/WidgetMenuBundle/releases/tag/3.0.0
